import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import NavigationMenuDemo from "./components/navbar";
import Snow from "./components/snow";
import Footer from "./components/footer";
import { CartProvider } from "./components/cardContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin", "cyrillic"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "i Space",
  description: "Generated by dog shit",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable} ${geistMono.variable} antialiased`}>
        <CartProvider>
          <NavigationMenuDemo />
          <Snow />
          {children}
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
